### ISSUE TITLE
HttpError: Not Found

### ISSUE THREAD

**Issue by lukasmalkmus** [z0al/dependent-issues#515]
Repeatedly saw this error in a workflow run:

```
HttpError: Not Found
    at /home/runner/work/_actions/z0al/dependent-issues/v1/webpack:/dependent-issues/node_modules/@octokit/request/dist-node/index.js:86:1
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Using latest version.

**Comment by z0al** [comment]
Hey. Do you have dependencies pointing to other private repositories?

**Comment by lukasmalkmus** [comment]
> Hey. Do you have dependencies pointing to other private repositories?

Sorry, can you elaborate? What kind of dependencies?

**Comment by z0al** [comment]
> If you mean issues pointing to other private repositories

Exactly. But that doesn't seem relevant based on your comment.

> But it does occur when it is run on schedule (I guess as it checks all PRs).

To make sure I understand. Are you saying the 404 issue happens for all PRs even those without any keywords?

**Comment by lukasmalkmus** [comment]
> To make sure I understand. Are you saying the 404 issue happens for all PRs even those without any keywords?

Sorry if I was unclear: The 404 issue happens **only** for PRs **with keywords**. It also happens when the workflow is run on a **schedule**, unrelated to a PR.

**Comment by z0al** [comment]
Got it. I can't think of something at the moment but will check when I get some free time

**Comment by johncardiologs** [comment]
I opened an issue for this @lukasmalkmus #535

**Comment by chrisoro** [comment]
I have the same problem as @lukasmalkmus. Wanted to run it on a GitHub Enterprise instance but always getting the following output:
```
##[debug]..Evaluating String:
##[debug]..=> 'HUB_API'
##[debug]=> '***'
##[debug]Result: '***'
##[debug]Evaluating condition for step: 'Run z0al/dependent-issues@v1'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: Run z0al/dependent-issues@v1
##[debug]Loading inputs
##[debug]Loading env
Run z0al/dependent-issues@v1
  with:
    label: dependent
    check_issues: off
    ignore_dependabot: on
    keywords: depends on, blocked by
    comment: This PR/issue depends on:
  {{ dependencies }}
  
  env:
    GITHUB_TOKEN: ***
::group::Context
Context
  Payload issue: #2
  ::endgroup::
::group::Checking #2
Checking #2
  No dependencies found. Running clean-up
  Error: HttpError: Not Found
      at /opt/app-root/src/_work/_actions/z0al/dependent-issues/v1/webpack:/dependent-issues/node_modules/@octokit/request/dist-node/index.js:8[6](https://XXX/TA/.chris_playground/actions/runs/1207258/job/2478010#step:2:6):1
      at processTicksAndRejections (node:internal/process/task_queues:[9](https://XXX/TA/.chris_playground/actions/runs/1207258/job/2478010#step:2:9)6:5)
  ##[debug]Node Action run completed with exit code 1
  ##[debug]Finishing: Run z0al/dependent-issues@v1
```
The action always fails and doesn't find dependencies. Is GHE not supported?
